### ISSUE TITLE
1楼

### ISSUE THREAD

**Issue by tingwen5** [xsi640/onlyoffice_demo#1]
修改后的文件拿着上次的md5密文访问新的md5密码会失败，无法打开修改后的文件，文件修改后，加密对的md5会改变

**Comment by xsi640** [comment]
文件修改后md5肯定会变，这些都取决于onlyoffice内部实现逻辑，onlyoffice内部定位一个文件用的实际上不是文件md5，md5是用来校验文件版本的。
